package ir.maktab.entitty.enums;

public enum Grade {
    ASSOCIATE,
    CONTINUOUS_BACHELORS,
    DISCONTINUOUS_BACHELORS,
    CONTINUOUS_MASTER,
    DISCONTINUOUS_MASTER,
    PHD,
    CONTINUOUS_PHD,
    DISCONTINUOUS_SPECIALIZED_DOCTORATE,
}
